### ISSUE TITLE
Incompatible with 8.1.x

### ISSUE THREAD

**Issue by MarcStoecker** [mindrevolution/Editor.js-for-Umbraco#12]
TypeError: Cannot read property 'src' of undefined

**Comment by mindrevolutiontk** [comment]
To support 8.0, it would be necessary to install a check that checks for image or file. Would that be an idea?

**Comment by MarcStoecker** [comment]
True. Well, I don't thing 8.0 will be a widely used version considering that 8.1 is here (despite being an catastrophic release qualitywise so far). But important to consider for future releases/versions! 👍

**Comment by MarcStoecker** [comment]
Please reopen, @mindrevolutiontk if latest from develop doesn't fix. I double checked with two sites and the fix is working as intended. Closing this.
