### ISSUE TITLE
Set default branch to "develop"

### ISSUE THREAD

**Issue by leekelleher** [mindrevolution/Editor.js-for-Umbraco#5]
@esn303 Can we set the default branch to "develop" please?

The reason for this is that any forks will use the default branch as the target for any pull requests. If this is "master", then we'd need to re-target each pull request to be "develop".  But if it's "develop", then we don't need to worry about that.

The option is under....
> `Settings > Branches > Default branch`

Thanks!

**Comment by MarcStoecker** [comment]
Makes sense! Done.
