### ISSUE TITLE
Upgrade Editor.js to v2.15

### ISSUE THREAD

**Issue by leekelleher** [mindrevolution/Editor.js-for-Umbraco#7]
Editor.js v2.15 was released today...

https://github.com/codex-team/editor.js/blob/master/docs/CHANGELOG.md#215

**Comment by MarcStoecker** [comment]
Ok, updated main library and the blocks. Let me know if it works for you -- if you find the time. Thanks!

**Comment by leekelleher** [comment]
Tested this morning. Working fine for me! 😄 Ace! 🎉
